#服务器配置
server:
  address: 127.0.0.1
  port: 8080

#数据库连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    druid:
      url: jdbc:mysql://127.0.0.1:3306/spring-boot-seed?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: root
      initial-size: 10
      min-idle: 10
      max-active: 20
      filter:
        stat:
          log-slow-sql: true
      driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis配置

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
